name: Deploy to VPS

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script_stop: true
          script: |
            cd ~/mybot

            # Экспорт всех секретов
            export SA_PASSWORD="${{ secrets.SA_PASSWORD }}"
            export RABBITMQ_USER="${{ secrets.RABBITMQ_USER }}"
            export RABBITMQ_PASS="${{ secrets.RABBITMQ_PASS }}"
            export TELEGRAM_TOKEN="${{ secrets.TELEGRAM_TOKEN }}"
            export REDIS_PASSWORD="${{ secrets.REDIS_PASSWORD }}"
            export DB_CONNECTION_STRING="Server=sqlserver,1433;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=true;Encrypt=false;"

            # Обновляем и запускаем контейнеры
            docker compose pull || true
            docker compose up -d --build
            docker image prune -f
